// ---------------------------------------------------------------------------
// SYNTHETIC norms — for TESTING / DEMO ONLY.
//
// These numbers are generated by code from the item counts. They are NOT the
// real Vineland norms and MUST NOT be used clinically. Their only purpose is to
// exercise the full scoring pipeline (v-scale → standard → percentile → ABC) so
// the app and the dummy data can be tested end-to-end.
// ---------------------------------------------------------------------------

import type {
  AgeBand,
  DomainId,
  DomainStandardRow,
  ItemsPack,
  NormsPack,
  RangeRow,
  SubdomainId,
} from "../types";

/** 24 contiguous raw-score buckets over 0..maxRaw → v-scale 1..24 (monotonic). */
function vScaleRanges(maxRaw: number): RangeRow<number>[] {
  const rows: RangeRow<number>[] = [];
  const n = 24;
  for (let v = 1; v <= n; v++) {
    const lo = Math.round(((v - 1) * (maxRaw + 1)) / n);
    let hi = Math.round((v * (maxRaw + 1)) / n) - 1;
    if (v === n) hi = maxRaw;
    if (hi < lo) hi = lo;
    rows.push({ min: lo, max: hi, value: v });
  }
  return rows;
}

/** Rough monotonic percentile from a standard score (mean 100, sd 15) — synthetic. */
function pctFromStandard(std: number): number {
  return Math.min(99, Math.max(1, Math.round(((std - 40) / 120) * 98 + 1)));
}

/** sum-of-v-scales (k subdomains) → domain standard score 20..160. */
function domainStandardRows(k: number): DomainStandardRow[] {
  const rows: DomainStandardRow[] = [];
  const lo = k * 1;
  const hi = k * 24;
  for (let s = lo; s <= hi; s++) {
    const std = Math.round(20 + ((s - lo) / (hi - lo)) * 140);
    rows.push({ sumVMin: s, sumVMax: s, standard: std, percentile: pctFromStandard(std) });
  }
  return rows;
}

/** sum of domain standards → ABC composite (synthetic average). */
function compositeRows(): DomainStandardRow[] {
  const rows: DomainStandardRow[] = [];
  for (let s = 0; s <= 700; s++) {
    const abc = Math.min(160, Math.max(20, Math.round(s / 4)));
    rows.push({ sumVMin: s, sumVMax: s, standard: abc, percentile: pctFromStandard(abc) });
  }
  return rows;
}

const AGE_BREAKS: [number, number][] = [
  [0, 35], [36, 47], [48, 59], [60, 71], [72, 95], [96, 143], [144, 215], [216, 600],
];

export function buildSyntheticNorms(pack: ItemsPack): NormsPack {
  const adaptiveSubs = pack.subdomains.filter((s) => s.domain !== "maladaptive");

  const rawToVScaleFor = (): AgeBand["rawToVScale"] => {
    const map: AgeBand["rawToVScale"] = {};
    for (const sd of adaptiveSubs) {
      const maxRaw = 2 * sd.items.length;
      map[sd.id as SubdomainId] = vScaleRanges(maxRaw);
    }
    return map;
  };

  const ageBands: AgeBand[] = AGE_BREAKS.map(([minMonths, maxMonths]) => ({
    minMonths,
    maxMonths,
    rawToVScale: rawToVScaleFor(),
  }));

  const domainStandard: Partial<Record<DomainId, DomainStandardRow[]>> = {};
  for (const d of pack.domains) {
    if (d.id === "maladaptive") continue;
    domainStandard[d.id] = domainStandardRows(d.subdomains.length);
  }

  return {
    edition: pack.edition,
    source: "SYNTHETIC — generated for testing/demo only. NOT real Vineland norms.",
    verified: false,
    ageBands,
    domainStandard,
    composite: compositeRows(),
  };
}
